### ISSUE TITLE
Can't `require'osv'.launch()`

### ISSUE THREAD

**Issue by andmis** [jbyuki/one-small-step-for-vimkind#14]
Hi, I'm trying to use OSV for the first time. I'm following the setup / quick-start instructions verbatim and getting an error:

```
E5108: Error executing lua Vim:Error invoking 'nvim_get_mode' on channel 3:
ch 3 sent an invalid message, closed.
stack traceback:
        [C]: in function 'rpcrequest'
        ...nvim/plugged/one-small-step-for-vimkind/lua/osv/init.lua:95: in function 'launch'
        [string ":lua"]:1: in main chunk
```

I'm using Neovim 0.7 from Homebrew and the latest versions of OSV and `nvim-dap` as of today. My `nvim-dap` is confirmed working (I can successfully use `nvim-dap-python`, for example).

**Comment by andmis** [comment]
Follow-up: I tracked this down to a problem with my vimrc. I had a line in my vimrc that writes to `/dev/stdout`, and you can't do that if you launch `nvim --headless --embed`, so `osv` was crashing while attempting to launch the child `nvim` instance.

So I'm going to close this issue, but I did have one question: when launching the child `nvim` instance, shouldn't we also pass the vimrc that was used by the launching instance of `nvim` with `-u` (at least when using `require 'osv'.run_this()`)?

**Comment by williamboman** [comment]
Some more tips for anyone else running into this as well: I had an `os.execute()` in my init script, which will produce its output to stdout in headless mode.
