### ISSUE TITLE
Can't toggle breakpoints after attached

### ISSUE THREAD

**Issue by andmis** [jbyuki/one-small-step-for-vimkind#15]
If I do the following:

1. Start `nvim my_file.lua`
2. `:lua require 'osv'.launch()`
3. Launch another `nvim my_file.lua`
4. Set a breakpoint in the second client
5. `:lua require 'dap'.continue()` → enter the host/port
6. `:luafile %` in the first client

...then execution stops at the breakpoint that I set, as it should. However, if I add or remove breakpoints in the second `nvim` client, it seems to have no effect. If I change the breakpoints and `:luafile %` in the first client, then execution stops at exactly the same set of breakpoints that were on when `require'dap'.continue` was called.

Is this expected?

**Comment by hiberabyss** [comment]
Could try https://github.com/hiberabyss/nvim-dbg, should solved the problem.

**Comment by hiberabyss** [comment]
Did not want go write `.t` files, and the project seems unmaintained.
