### ISSUE TITLE
[Not work for lua functions] breakpoint in function not worked if not called in the lua file

### ISSUE THREAD

**Issue by hiberabyss** [jbyuki/one-small-step-for-vimkind#16]
If set breakpoint on function that will be called after the lua file loaded, seems the breakpoint not work.

**Comment by hiberabyss** [comment]
Refactored plugin https://github.com/hiberabyss/nvim-dbg solved the problem.

**Comment by jbyuki** [comment]
Did it solve the breakpoint issue in the refactored plugin?
