### ISSUE TITLE
Is port number correct?

### ISSUE THREAD

**Issue by kay-adamof** [jbyuki/one-small-step-for-vimkind#22]
https://github.com/jbyuki/one-small-step-for-vimkind/blob/fa0df0ade3402c44190147da7d0f766254ebcbeb/doc/osv.txt#L71

port number is `8088`

But in README.md;

`8086`.

It worked correctly with `8086`.

**Comment by jbyuki** [comment]
Good catch, that's an oversight.
If you can PR that, it would be great. It would credit you as the contributor.
