### ISSUE TITLE
Any instruction on how to get the debugger going using LunarVim?

### ISSUE THREAD

**Issue by mpas** [jbyuki/one-small-step-for-vimkind#23]
I am using LunarVim and would love to try the debugger but as mentioned something needs to be done with a config file. I am not sure what to do!!!

I have installed the debugger and when i try to launch the debugger i get the following error message:

```
E5108: Error executing lua Vim:Error invoking 'nvim_exec_lua' on channel 517:
Error executing lua: [string "<nvim>"]:1: module 'osv' not found:
```

**Comment by jbyuki** [comment]
I have never tried LunarVim but you should be able to launch the osv server with the LunarVim's config file with `require".osv".launch({config_file = "PATH_TO_LUNAR_VIM_CONFIG_FILE", port = 8086 })`. But I can try to check here if it really works tonight.

**Comment by mpas** [comment]
I tried the following when having a .lua file open.

`:lua require".osv".launch({config_file = "~/.config/lvim/config.lua", port = 8086 })`

The result was en error.
```
E5108: Error executing lua Vim:Error invoking 'nvim_get_mode' on channel 3:
ch 3 was closed by the client
stack traceback:
        [C]: in function 'rpcrequest'
        ...acker/start/one-small-step-for-vimkind/lua//osv/init.lua:106: in function 'launch'
        [string ":lua"]:1: in main chunk
```

Maybe i am doing something wrong overhere.

**Comment by jbyuki** [comment]
I have added a new flag for LunarVim users. See the README for how to use it, it should be fairly straightforward. Let me know if this works now. Note that `run_this` is still not supported with LunarVim but I'm guessing nobody is using it.

**Comment by hawkinchina** [comment]
@mpas I met the same error with LunarVim. it is ok now ?

**Comment by mpas** [comment]
@hawkinchina Yep it works now!

**Comment by hawkinchina** [comment]
log info:
E5108: Error executing lua ...are/lunarvim/site/pack/packer/start/nvim-dap/lua/dap.lua:343: ...are/lunarvim/site
/pack/packer/start/nvim-dap/lua/dap.lua:746: Adapter used with attach must have a port property
stack traceback:
        [C]: in function 'trigger_run'
        ...are/lunarvim/site/pack/packer/start/nvim-dap/lua/dap.lua:343: in function 'run'
        ...are/lunarvim/site/pack/packer/start/nvim-dap/lua/dap.lua:282: in function 'cb'
        .../lunarvim/site/pack/packer/start/nvim-dap/lua/dap/ui.lua:34: in function 'pick_if_many'
        ...are/lunarvim/site/pack/packer/start/nvim-dap/lua/dap.lua:276: in function 'select_config_and_run'
        ...are/lunarvim/site/pack/packer/start/nvim-dap/lua/dap.lua:636: in function 'continue'
        [string ":lua"]:1: in main chunk


---
config.lua
require("dap").set_log_level("DEBUG")
dap.configurations.lua = {
	{
		type = "nlua",
		request = "attach",
		name = "Attach to running Neovim instance",
	},
}

dap.adapters.nlua = function(callback, config)
	callback({ type = "server", host = "config.host", port = config.port })
end

-- Set keybindings to interact with the nvim-dap client.
vim.api.nvim_set_keymap("n", "<F8>", [[:lua require"dap".toggle_breakpoint()<CR>]], { noremap = true })
vim.api.nvim_set_keymap("n", "<F9>", [[:lua require"dap".continue()<CR>]], { noremap = true })
vim.api.nvim_set_keymap("n", "<F10>", [[:lua require"dap".step_over()<CR>]], { noremap = true })
vim.api.nvim_set_keymap("n", "<S-F10>", [[:lua require"dap".step_into()<CR>]], { noremap = true })
vim.api.nvim_set_keymap("n", "<F12>", [[:lua require"dap.ui.widgets".hover()<CR>]], { noremap = true })

vim.api.nvim_set_keymap("n", "<F5>", [[:lua require"osv".launch({port = 8086, lvim = true})<CR>]], { noremap = true })

**Comment by jbyuki** [comment]
> dap.adapters.nlua = function(callback, config)
> callback({ type = "server", host = "config.host", port = config.port })
> end

See the README for a correct configuration for the adapter.

**Comment by hawkinchina** [comment]
ok, I changed the adapter configuration
---
dap.adapters.nlua = function(callback, config)
  callback({ type = 'server', host = config.host or "127.0.0.1", port = config.port or 8086 })
end
---
push F9,  dap UI display, but cannot step into or step over.

**Comment by jbyuki** [comment]
If you just debug a lua script, the procedure is as follows:

* Put breakpoints where you need to
* Toggle `nvim-dap-ui` (optional)
* Call `lua require"osv".run_this({lvim=true})` pass `lvim=true` in case you're using LunarVim otherwise not

The execution should then stop at the breakpoint. 

Note that `one-small-step-for-vimkind` is not just a lua debugger but specially targeted to debug neovim plugins. So you would probably use `launch()` instead. See documentation.

**Comment by hawkinchina** [comment]
ok, thanks @jbyuki

**Comment by jbyuki** [comment]
Keep the issue to one topic.  Please open a new issue for that. 

For the question at hand, I already gave an answer [here](https://github.com/jbyuki/one-small-step-for-vimkind/issues/13) under **print statements in [dap.repl]**. See if that helps, again `osv` is not meant to be a general lua debugger but specifically targeted to debug neovim plugins.

**Comment by AntoineBalaine** [comment]
Sorry to be necro-bumping, but this might be useful to others who come on this thread later on. 
I was getting this error when running this with lunarvim:
```bash
E5108: Error executing lua Vim:E475: Invalid value for argument cmd: 'lvim' is not executable
stack traceback:
        [C]: in function 'jobstart'
        ...ack/lazy/opt/one-small-step-for-vimkind/lua/osv/init.lua:1267: in function 'run_this'
        [string ":lua"]:1: in main chunk
```
For some reason the `lvim` executable  couldn't be found by vimkind, so I got it fixed by adding these two lines right before the call to `vim.fn.jobstart`:
```lua
if args[1] == "lvim" then
  args[1] == "nvim"
end
```
Hope this helps…
