### ISSUE TITLE
Print value of global variable?

### ISSUE THREAD

**Issue by Maltimore** [jbyuki/one-small-step-for-vimkind#27]
Hi,
sorry this is (probably) more of a usage question than a bug report, but I didn't know where to ask questions.
I'm using this plugin with some success, but I noticed that in the REPL, I can only print the value of function-local variables (variables of the function where the debugger is currently stopped). When I try to print a variable of the enclosing scope (the module), I get "nil". Is there a way around that?

**Comment by jbyuki** [comment]
Can you provide a reproducible example possibly? I'm not sure if it's about upvalues (which should also be supported) or something else.

**Comment by jbyuki** [comment]
Please reopen if required.
