### ISSUE TITLE
How to debug Lua scripts in Unreal Engine？

### ISSUE THREAD

**Issue by luoxz-ai** [jbyuki/one-small-step-for-vimkind#29]
Self-debugging, variables are ok, the output function will not be printed to the console

How to debug unlua of Unreal Engine, this is a very interesting thing, he uses Luapanda

https://github.com/Tencent/UnLua

https://github.com/Tencent/LuaPanda

**Comment by jbyuki** [comment]
1. Yes, printing to console is not supported. I invite you to read [this](https://github.com/jbyuki/one-small-step-for-vimkind/issues/13#issuecomment-1255404427) issue which talks about it.

2. This plugin is only meant to be used with Neovim. Other systems are not considered at the moment.
