### ISSUE TITLE
Evaluation only displays an empty rectangle

### ISSUE THREAD

**Issue by Quessou** [jbyuki/one-small-step-for-vimkind#34]
I am trying to setup one-small-step-for-vimkind and make it work with nvim-dap, and it seems like everything is working, but I do not manage to make the plugin add a watch or evaluate a value on the fly :
![evaluation](https://user-images.githubusercontent.com/8946520/234808621-942a6b82-8939-4786-86df-8aaf5f509acd.png)

Since I manage to do it with a Python debugger and the same nvim-dap, I guess the issue comes from either one-small-step-for-vimkind or (probably) my configuration.

Versions/Commits hashes :
one-small-step-for-vimkind : `27e5f59` 
nvim-dap : `6cedcb5`

My config for the DAP is the following :
```lua
local dap = require('dap')

dap.configurations.lua = {
	{
		type = "nlua",
		request = "attach",
		name = "Attach to running Neovim instance",
		host = function()
			local value = vim.fn.input "Host [127.0.0.1]: "
			if value ~= "" then
				return value
			end
			return "127.0.0.1"
		end,
		port = function()
			local val = tonumber(vim.fn.input("Port: ", "54321"))
			assert(val, "Please provide a port number")
			return val
		end,
	},
}

dap.adapters.nlua = function(callback, config)
	callback { type = "server", host = config.host, port = config.port, log = true }
end
```

Obviously, I don't exclude having made a stupid mistake somewhere due to my lack of experience with configuring vim and LUA :grimacing:

**Comment by jbyuki** [comment]
The configuration looks fine although I would suggest using the new one available in the README. It is shorter and allows you to connect without entering the port when connecting with `launch()`. With `run_this()` it doesn't make a difference as you doesn't require one anyway. 

It's suprising to see that you can get the virtual annotations with values but not inspect the values. What function of `nvim-dap` do you use for inspecting? Not sure about active watches, this is maybe not supported.

**Comment by jbyuki** [comment]
Could you try with the command binded to `<F12>` available in the readme?
That's what I use and should work. I will take a look at `eval` and see
what is happening there.

**Comment by jbyuki** [comment]
I see the issue now, I didn't implement context hovers which is clearly said that it's not supported in the osv log 😄  I will see if I can implement that so you can use `nvim-dap-ui` as well.

**Comment by jbyuki** [comment]
I've added a crude implementation of context hovers, let me know if this works now.
