### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ur4ltz** [jbyuki/one-small-step-for-vimkind#4]
Hi!
In README.md reads 

>Install
After installing one-small-step-for-vimkind, you will also need a DAP plugin which will allow you to interact with the adapter. 

Please update Install instruction!

**Comment by jbyuki** [comment]
Hi,
I added some instructions in the README 😃 
Tell if that's what you're looking for.

**Comment by ur4ltz** [comment]
Yes! 
I will now start configuring from 'wbthomason/packer.nvim'.
```lua
  use {
    'mfussenegger/nvim-dap',
    requires = {
      {'jbyuki/one-small-step-for-vimkind'},
    }
  }
```

**Comment by jbyuki** [comment]
Great, I'll close the issue for now.

I'm not familiar with packer.nvim but maybe it should be:

```
use 'mfussenegger/nvim-dap'
use 'jbyuki/one-small-step-for-vimkind'
```

Because there are not direct dependencies.

**Comment by alexzanderr** [comment]
these 2 are similar, by puttin requires you just tell to install it if its not presend and load it accordingly.
