### ISSUE TITLE
How to debug non-neovim lua code?

### ISSUE THREAD

**Issue by vatosarmat** [jbyuki/one-small-step-for-vimkind#5]
Suppose I have a standalone `main.lua` with `#!/usr/bin/lua` which does some smart and tricky suftt and therefore it is complicated and therefore I need a debugger with breakpoints to debug it. How to run `main.lua` under OSV? Maybe there should be an instruction for that

**Comment by jbyuki** [comment]
If you can run your script using the embedded lua debugger ( luajit 2.1 ) just go ahead and invoke `run_this()` with the script open. If you want to use an external lua interpreter I'm afraid it's currently not possible.  Have you looked at [lua-debug](https://github.com/actboy168/lua-debug)?

**Comment by jbyuki** [comment]
It would perfectly possible for me to implement debugging for non-Neovim code, it's just that I never use it outside Neovim so I didn't build any.

**Comment by vatosarmat** [comment]
Ok, thanks. Could you hint what are the diffs between `.lua.t` files and just `.lua`? and where `@annotations` in `.lua.t` come from?

**Comment by jbyuki** [comment]
Sure, I'm coding in the `lua.t` files which in turn generate the `lua` files using a literate programming plugin called [ntangle.nvim](https://github.com/jbyuki/ntangle.nvim). I've coded the past year with it and sticky with it for the moment. 

If you want you can install the plugin and it should be ready to use. The docs also explain about the syntax. I would be happy to review any PR.
