### ISSUE TITLE
Dependency requirements?

### ISSUE THREAD

**Issue by MikeLemo1** [jbyuki/one-small-step-for-vimkind#50]
Is it possible that other than installing NVim, Lazy, and nvim-dap one-small-step-for-vimkind requires other installation and config say like vscode debugger for the lua part? https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#local-lua-debugger-vscode

**Comment by jbyuki** [comment]
See the [automated tests](https://github.com/jbyuki/one-small-step-for-vimkind/actions/runs/9257941741/job/25467095984) run in this repo. The only dependency it adds from a fresh install is `nvim-dap`. With proper configuration, it should work. Please describe the issue you are facing with `launch` so I can help.

**Comment by MikeLemo1** [comment]
READ BEFORE:
I'm currently doing the tesing on a simple "hello_wrold.lua" in "~/my_folder/code/lua/examples/hello_world.lua"
```lua
local a = 10

local x = 55
print("Hello from the other siddee!!")
x = 20
print("You must've called a toughnd timess!!")
a = 5234
print("You must've called a toughnd timess!!")
print(a)
```

and the test works by normally opening the file placing a couple of breakpoints and then 
`require("dap").continue()`
choose the `Run this file` option (attach to neovim instance is also a possibility I'll want to test and make work later after taking care of the root problems before starting to actually debug the neovim's lua instance)

the enter `x` or `y` to the expression list
Then finally continue (pressing the green continue gui button with the mouse)
---------------------------------------------------------------------------------------------------------------------------------

Now with the LazyVim setup after installing the `debugpy` dap adapter from mason debugging python (with the dap-ui) works as expected with the watch list and repl console `print()` output 
what else after installing `:LazyExtras`  `● dap.nlua  nvim-dap  one-small-step-for-vimkind` do you have to do it LazyVim to make lua dap work fully like `debugpy`?

**Comment by jbyuki** [comment]
All I can say is for the printing, one important rule for any github issue is to check for opened issues. There are 6 opened in this repo which is very few and one is exactly talking about it. 

I will close this issue because I don't see any problem as it seems to work for you now.
