### ISSUE TITLE
Feature request: Add a way to stop the debuggee; Implement exited and terminated events

### ISSUE THREAD

**Issue by b0o** [jbyuki/one-small-step-for-vimkind#8]
After I've finished debugging, I'd like to stop the debugger and associated processes. Currently with osv that doesn't seem possible.

**Comment by jbyuki** [comment]
I added a `require"osv".stop()` which should do just that. Could you test with the latest commit. If it works, you can close this issue.

**Comment by b0o** [comment]
Apologies for the delay; I just got a chance to test this and it's working. Thank you @jbyuki!
